name: SIEM
on: push
jobs:
  WelcomePage:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Steps
        run: |
          echo "Welcome to GHA"
          echo "This is line two"
          echo "This is line three"
         
            
