name: SIEM
on: 
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*    

jobs:
  WelcomePage:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Steps
        run: |
          echo "Welcome to GHA"
          echo "This is line two"
          echo "This is line three"
         
            
